version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    environment:
      ${JWT_KEY}
    link:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      ${MONGODB_URL}
  redis:
    container_name: myapp-redis
    image: 'redis:4.0.11'
    expose:
      - 6379
    environment:
      ${SECRET}
      ${KEY}
      ${TREE}